### ISSUE TITLE
JobHandle's reduced output not available in 0.1.0

### ISSUE THREAD

**Issue by Aknilam** [boalang/api#1]
There is method which allows to download part of output: https://github.com/boalang/api/blob/master/Java/src/edu/iastate/cs/boa/JobHandle.java#L210. Unfortunately, this is not available in 0.1.0 version http://boa.cs.iastate.edu/docs/api/0.1.0/.

It would be useful to provide also some metadata about job output (lines count, chars count).

**Comment by psybers** [comment]
Yes, but isn't this method available in 0.1.0?

https://github.com/boalang/api/blob/master/Java/src/edu/iastate/cs/boa/JobHandle.java#L197

**Comment by psybers** [comment]
http://boa.cs.iastate.edu/docs/api/0.1.0/edu/iastate/cs/boa/JobHandle.html#getOutput()

**Comment by Aknilam** [comment]
I'm asking about this https://github.com/boalang/api/blob/master/Java/src/edu/iastate/cs/boa/JobHandle.java#L210 method, not this one https://github.com/boalang/api/blob/master/Java/src/edu/iastate/cs/boa/JobHandle.java#L197.

**Comment by psybers** [comment]
I guess I don't know what you are asking for.  0.1.0 is already released.  We can't change the API of a released version.  And you linked to a new API, that will clearly be in the next release.

**Comment by psybers** [comment]
I'm closing this issue as there is a new release of the API.
